export const MARKET_PRODUCTS = [
  {
    id: 'm1',
    title: 'Classic Wristwatch',
    name: 'Classic Wristwatch',
    price: 12999, // in cents for formatting
    originalPrice: 17999,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 124,
    category: 'Electronics',
    location: 'New York, NY',
    description: 'A timeless classic wristwatch featuring a premium leather strap and precision Swiss movement. This elegant timepiece combines traditional craftsmanship with modern reliability. Perfect for both formal occasions and everyday wear.',
    specifications: {
      'Movement': 'Swiss Quartz',
      'Case Material': 'Stainless Steel',
      'Strap': 'Genuine Leather',
      'Water Resistance': '50 meters',
      'Warranty': '2 years',
    },
    features: [
      'Premium Leather Strap',
      'Scratch-resistant Crystal',
      'Date Display',
      'Luminous Hands',
      '2-Year Warranty',
    ],
    inStock: true,
    seller: {
      name: 'Timepiece Experts',
      avatar: 'https://i.pravatar.cc/150?img=12',
      rating: 4.9,
      reviews: 523,
      verified: true,
    },
  },
  {
    id: 'm2',
    title: 'Running Shoes',
    name: 'Running Shoes',
    price: 8950,
    originalPrice: 12900,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 89,
    category: 'Apparel',
    location: 'Los Angeles, CA',
    description: 'High-performance running shoes designed for maximum comfort and durability. Features advanced cushioning technology, breathable mesh upper, and superior traction. Ideal for daily runs, training, and athletic activities.',
    specifications: {
      'Material': 'Mesh & Synthetic',
      'Weight': '280g per shoe',
      'Drop Height': '8mm',
      'Cushioning': 'Air-cushioned',
      'Size Range': '7-13 US',
    },
    features: [
      'Breathable Mesh Upper',
      'Air Cushioning Technology',
      'Anti-slip Outsole',
      'Lightweight Design',
      '30-Day Return Policy',
    ],
    inStock: true,
    seller: {
      name: 'Sport Gear Pro',
      avatar: 'https://i.pravatar.cc/150?img=15',
      rating: 4.7,
      reviews: 342,
      verified: true,
    },
  },
  {
    id: 'm3',
    title: 'Eau de Parfum',
    name: 'Eau de Parfum',
    price: 7500,
    originalPrice: 9500,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 256,
    category: 'Apparel',
    location: 'Paris, France',
    description: 'Luxury fragrance with notes of bergamot, jasmine, and sandalwood. A sophisticated scent that lasts throughout the day. Elegantly packaged in a beautiful glass bottle with gold accents.',
    specifications: {
      'Volume': '100ml',
      'Concentration': 'Eau de Parfum',
      'Fragrance Family': 'Floral Woody',
      'Longevity': '8-10 hours',
      'Sillage': 'Moderate to Strong',
    },
    features: [
      'Premium Fragrance',
      'Long-lasting Formula',
      'Elegant Packaging',
      'Gift Box Included',
      'Satisfaction Guaranteed',
    ],
    inStock: true,
    seller: {
      name: 'Luxury Fragrances',
      avatar: 'https://i.pravatar.cc/150?img=8',
      rating: 4.8,
      reviews: 678,
      verified: true,
    },
  },
  {
    id: 'm4',
    title: 'Wireless Headphones',
    name: 'Wireless Headphones',
    price: 19900,
    originalPrice: 24900,
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 445,
    category: 'Electronics',
    location: 'San Francisco, CA',
    description: 'Premium wireless over-ear headphones with active noise cancellation. Delivers crystal-clear audio with deep bass and crisp highs. Features Bluetooth 5.0, 30-hour battery life, and premium comfort padding.',
    specifications: {
      'Driver Size': '40mm',
      'Frequency Response': '20Hz - 20kHz',
      'Battery Life': '30 hours',
      'Bluetooth': '5.0',
      'Noise Cancellation': 'Active',
    },
    features: [
      'Active Noise Cancellation',
      '30-Hour Battery Life',
      'Premium Sound Quality',
      'Comfortable Fit',
      'Fast Charging',
    ],
    inStock: true,
    seller: {
      name: 'AudioTech Store',
      avatar: 'https://i.pravatar.cc/150?img=20',
      rating: 4.9,
      reviews: 892,
      verified: true,
    },
  },
  {
    id: 'm5',
    title: 'Ultrabook Laptop',
    name: 'Ultrabook Laptop',
    price: 99999,
    originalPrice: 129999,
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 312,
    category: 'Electronics',
    location: 'Seattle, WA',
    description: 'High-performance ultrabook with Intel Core i7 processor, 16GB RAM, and 512GB SSD. Features a stunning 14-inch display, long battery life, and premium aluminum build. Perfect for professionals and creators.',
    specifications: {
      'Processor': 'Intel Core i7-1165G7',
      'RAM': '16GB DDR4',
      'Storage': '512GB NVMe SSD',
      'Display': '14" FHD IPS',
      'Battery': 'Up to 12 hours',
    },
    features: [
      'Intel Core i7 Processor',
      '16GB RAM & 512GB SSD',
      '14" Full HD Display',
      '12-Hour Battery Life',
      'Premium Aluminum Design',
    ],
    inStock: true,
    seller: {
      name: 'Tech Hub',
      avatar: 'https://i.pravatar.cc/150?img=25',
      rating: 4.8,
      reviews: 1245,
      verified: true,
    },
  },
  {
    id: 'm6',
    title: 'Leather Boots',
    name: 'Leather Boots',
    price: 14500,
    originalPrice: 18900,
    image: 'https://images.unsplash.com/photo-1605812860427-4024433d70fd?w=800&h=800&fit=crop',
    rating: 4.5,
    reviews: 167,
    category: 'Apparel',
    location: 'Milan, Italy',
    description: 'Handcrafted genuine leather boots with superior durability and style. Features a comfortable cushioned insole, sturdy rubber sole, and classic design. Perfect for both casual and semi-formal occasions.',
    specifications: {
      'Material': 'Genuine Leather',
      'Sole': 'Rubber',
      'Closure': 'Lace-up',
      'Heel Height': '2 inches',
      'Size Range': '7-12 US',
    },
    features: [
      'Genuine Leather',
      'Handcrafted Quality',
      'Comfortable Fit',
      'Durable Construction',
      'Classic Design',
    ],
    inStock: true,
    seller: {
      name: 'Leather Craft Co.',
      avatar: 'https://i.pravatar.cc/150?img=30',
      rating: 4.6,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm7',
    title: 'Smartphone Pro Max',
    name: 'Smartphone Pro Max',
    price: 79900,
    originalPrice: 99900,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 567,
    category: 'Electronics',
    location: 'San Francisco, CA',
    description: 'Latest generation smartphone with advanced camera system, 5G connectivity, and all-day battery life. Features a stunning OLED display, powerful processor, and premium build quality.',
    specifications: {
      'Display': '6.7" OLED',
      'Storage': '256GB',
      'RAM': '8GB',
      'Camera': '48MP Triple Camera',
      'Battery': '4500mAh',
    },
    features: [
      '5G Connectivity',
      'Advanced Camera System',
      'Face ID & Touch ID',
      'Wireless Charging',
      '2-Year Warranty',
    ],
    inStock: true,
    seller: {
      name: 'Tech Innovations',
      avatar: 'https://i.pravatar.cc/150?img=35',
      rating: 4.8,
      reviews: 1023,
      verified: true,
    },
  },
  {
    id: 'm8',
    title: 'Designer Sunglasses',
    name: 'Designer Sunglasses',
    price: 15900,
    originalPrice: 24900,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 289,
    category: 'Apparel',
    location: 'Milan, Italy',
    description: 'Premium designer sunglasses with UV400 protection, polarized lenses, and lightweight frame. Stylish design that combines fashion with function. Includes protective case.',
    specifications: {
      'Lens Material': 'Polycarbonate',
      'UV Protection': 'UV400',
      'Frame': 'Acetate',
      'Lens Type': 'Polarized',
      'Case Included': 'Yes',
    },
    features: [
      'UV400 Protection',
      'Polarized Lenses',
      'Lightweight Frame',
      'Protective Case',
      '1-Year Warranty',
    ],
    inStock: true,
    seller: {
      name: 'Style Optics',
      avatar: 'https://i.pravatar.cc/150?img=40',
      rating: 4.7,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm9',
    title: 'Fitness Tracker Watch',
    name: 'Fitness Tracker Watch',
    price: 19900,
    originalPrice: 29900,
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 432,
    category: 'Electronics',
    location: 'Boston, MA',
    description: 'Advanced fitness tracker with heart rate monitoring, sleep tracking, and 20+ sports modes. Waterproof design, 7-day battery life, and smartphone notifications.',
    specifications: {
      'Display': '1.4" Color Touchscreen',
      'Battery': '7 days',
      'Water Resistance': '5 ATM',
      'Sensors': 'Heart Rate, GPS, Accelerometer',
      'Compatibility': 'iOS & Android',
    },
    features: [
      'Heart Rate Monitoring',
      'Sleep Tracking',
      'GPS Built-in',
      'Waterproof Design',
      'Smart Notifications',
    ],
    inStock: true,
    seller: {
      name: 'Active Gear Store',
      avatar: 'https://i.pravatar.cc/150?img=45',
      rating: 4.8,
      reviews: 678,
      verified: true,
    },
  },
  {
    id: 'm10',
    title: 'Cotton T-Shirt Pack',
    name: 'Cotton T-Shirt Pack',
    price: 3999,
    originalPrice: 5999,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop',
    rating: 4.5,
    reviews: 156,
    category: 'Apparel',
    location: 'New York, NY',
    description: 'Premium pack of 3 cotton t-shirts in various colors. Made from 100% organic cotton, soft to touch, and durable. Perfect for everyday wear.',
    specifications: {
      'Material': '100% Organic Cotton',
      'Pack Size': '3 Shirts',
      'Care': 'Machine Washable',
      'Sizes': 'S, M, L, XL',
      'Colors': 'White, Black, Gray',
    },
    features: [
      '100% Organic Cotton',
      'Pack of 3',
      'Multiple Colors',
      'Soft & Comfortable',
      'Eco-Friendly',
    ],
    inStock: true,
    seller: {
      name: 'Eco Fashion',
      avatar: 'https://i.pravatar.cc/150?img=50',
      rating: 4.6,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm11',
    title: 'Gaming Mouse',
    name: 'Gaming Mouse',
    price: 6999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 678,
    category: 'Electronics',
    location: 'Seattle, WA',
    description: 'High-performance gaming mouse with RGB lighting, customizable buttons, and precision tracking. Perfect for gaming and professional use. Ergonomic design for extended use.',
    specifications: {
      'DPI': 'Up to 16000',
      'Buttons': '7 Programmable',
      'Connectivity': 'Wired & Wireless',
      'Weight': '85g',
      'Sensor': 'Optical',
    },
    features: [
      'RGB Lighting',
      'Programmable Buttons',
      'Wireless & Wired',
      'Ergonomic Design',
      'Gaming Software',
    ],
    inStock: true,
    seller: {
      name: 'Gaming Tech',
      avatar: 'https://i.pravatar.cc/150?img=55',
      rating: 4.9,
      reviews: 890,
      verified: true,
    },
  },
  {
    id: 'm12',
    title: 'Yoga Mat Premium',
    name: 'Yoga Mat Premium',
    price: 4499,
    originalPrice: 6999,
    image: 'https://images.unsplash.com/photo-1601925260368-802935ebb8e2?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 321,
    category: 'Sports',
    location: 'Los Angeles, CA',
    description: 'Eco-friendly yoga mat with superior grip, cushioning, and durability. Non-slip surface, moisture-wicking properties, and extra thick padding for comfort.',
    specifications: {
      'Material': 'TPE (Eco-friendly)',
      'Thickness': '6mm',
      'Dimensions': '72" x 24"',
      'Weight': '2.5 lbs',
      'Colors': 'Multiple Options',
    },
    features: [
      'Non-slip Surface',
      'Extra Thick Padding',
      'Moisture Wicking',
      'Eco-friendly Material',
      'Carry Strap Included',
    ],
    inStock: true,
    seller: {
      name: 'Fitness Essentials',
      avatar: 'https://i.pravatar.cc/150?img=60',
      rating: 4.7,
      reviews: 567,
      verified: true,
    },
  },
  // Real Estate
  {
    id: 'm13',
    title: 'Modern 2BR Apartment',
    name: 'Modern 2BR Apartment',
    price: 25000000,
    originalPrice: 27500000,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 45,
    category: 'Real Estate',
    location: 'New York, NY',
    description: 'Beautiful modern 2-bedroom apartment in the heart of the city. Recently renovated with high-end finishes, large windows, and stunning city views.',
    specifications: {
      'Bedrooms': '2',
      'Bathrooms': '2',
      'Square Feet': '1,200 sq ft',
      'Year Built': '2020',
      'Parking': '1 Space',
    },
    features: [
      'Modern Renovation',
      'City Views',
      'High-End Finishes',
      'Pet Friendly',
      'Parking Included',
    ],
    inStock: true,
    seller: {
      name: 'Elite Properties',
      avatar: 'https://i.pravatar.cc/150?img=11',
      rating: 4.9,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm14',
    title: 'Luxury House with Garden',
    name: 'Luxury House with Garden',
    price: 85000000,
    originalPrice: 95000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 32,
    category: 'Real Estate',
    location: 'Los Angeles, CA',
    description: 'Stunning luxury house featuring spacious rooms, private garden, swimming pool, and modern amenities. Perfect for families seeking elegance and comfort.',
    specifications: {
      'Bedrooms': '4',
      'Bathrooms': '3',
      'Square Feet': '3,500 sq ft',
      'Year Built': '2018',
      'Lot Size': '0.5 acres',
    },
    features: [
      'Private Garden',
      'Swimming Pool',
      'Modern Kitchen',
      'Home Office',
      'Gated Community',
    ],
    inStock: true,
    seller: {
      name: 'Premium Realty',
      avatar: 'https://i.pravatar.cc/150?img=22',
      rating: 4.8,
      reviews: 156,
      verified: true,
    },
  },
  // Jobs
  {
    id: 'm15',
    title: 'Senior Software Engineer',
    name: 'Senior Software Engineer',
    price: 150000,
    originalPrice: 180000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 28,
    category: 'Jobs',
    location: 'San Francisco, CA',
    description: 'Full-time remote position for experienced software engineer. Work with cutting-edge technologies, competitive salary, and excellent benefits package.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '5+ years',
      'Remote': 'Yes',
      'Benefits': 'Health, Dental, 401k',
      'Salary Range': '$150k - $180k',
    },
    features: [
      'Remote Work',
      'Competitive Salary',
      'Health Benefits',
      'Stock Options',
      'Flexible Hours',
    ],
    inStock: true,
    seller: {
      name: 'Tech Innovations Inc',
      avatar: 'https://i.pravatar.cc/150?img=33',
      rating: 4.8,
      reviews: 89,
      verified: true,
    },
  },
  {
    id: 'm16',
    title: 'Marketing Manager Position',
    name: 'Marketing Manager Position',
    price: 95000,
    originalPrice: 110000,
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 19,
    category: 'Jobs',
    location: 'New York, NY',
    description: 'Dynamic marketing manager role for creative professional. Lead marketing campaigns, manage team, and drive brand growth in fast-paced environment.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '3+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Full Package',
      'Salary Range': '$95k - $110k',
    },
    features: [
      'Creative Environment',
      'Growth Opportunities',
      'Team Leadership',
      'Flexible Schedule',
      'Career Development',
    ],
    inStock: true,
    seller: {
      name: 'Creative Agency',
      avatar: 'https://i.pravatar.cc/150?img=44',
      rating: 4.7,
      reviews: 67,
      verified: true,
    },
  },
  // Services
  {
    id: 'm17',
    title: 'Web Design Services',
    name: 'Web Design Services',
    price: 2500,
    originalPrice: 3500,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 124,
    category: 'Services',
    location: 'Remote',
    description: 'Professional web design services including custom website creation, responsive design, SEO optimization, and ongoing maintenance support.',
    specifications: {
      'Delivery Time': '2-4 weeks',
      'Revisions': 'Unlimited',
      'Support': '3 months included',
      'Responsive': 'Yes',
      'SEO Included': 'Yes',
    },
    features: [
      'Custom Design',
      'Responsive Layout',
      'SEO Optimized',
      'Mobile Friendly',
      'Ongoing Support',
    ],
    inStock: true,
    seller: {
      name: 'Design Studio Pro',
      avatar: 'https://i.pravatar.cc/150?img=55',
      rating: 4.9,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm18',
    title: 'Digital Marketing Package',
    name: 'Digital Marketing Package',
    price: 1500,
    originalPrice: 2000,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 89,
    category: 'Services',
    location: 'Remote',
    description: 'Comprehensive digital marketing package including social media management, content creation, email campaigns, and analytics reporting.',
    specifications: {
      'Duration': '3 months',
      'Platforms': 'All Major',
      'Content': 'Custom Created',
      'Analytics': 'Included',
      'Support': '24/7',
    },
    features: [
      'Social Media Management',
      'Content Creation',
      'Email Campaigns',
      'Analytics Reports',
      'Strategy Development',
    ],
    inStock: true,
    seller: {
      name: 'Marketing Experts',
      avatar: 'https://i.pravatar.cc/150?img=66',
      rating: 4.8,
      reviews: 234,
      verified: true,
    },
  },
  // Vehicles
  {
    id: 'm19',
    title: '2023 BMW M3',
    name: '2023 BMW M3',
    price: 7500000,
    originalPrice: 8500000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 67,
    category: 'Vehicles',
    location: 'Miami, FL',
    description: 'Brand new 2023 BMW M3 with sport package, premium interior, and advanced technology features. Low mileage, perfect condition, fully serviced.',
    specifications: {
      'Year': '2023',
      'Mileage': '2,500 miles',
      'Engine': '3.0L Twin Turbo',
      'Transmission': 'Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      'Sport Package',
      'Premium Interior',
      'Advanced Safety',
      'Navigation System',
      'Warranty Included',
    ],
    inStock: true,
    seller: {
      name: 'Luxury Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=77',
      rating: 4.9,
      reviews: 189,
      verified: true,
    },
  },
  {
    id: 'm20',
    title: '2022 Tesla Model Y',
    name: '2022 Tesla Model Y',
    price: 5500000,
    originalPrice: 6200000,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad054513bb?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 94,
    category: 'Vehicles',
    location: 'San Francisco, CA',
    description: 'Electric SUV with autopilot, long range battery, and premium features. Single owner, excellent condition, all service records available.',
    specifications: {
      'Year': '2022',
      'Mileage': '12,000 miles',
      'Range': '330 miles',
      'Autopilot': 'Full Self-Driving',
      'Charging': 'Supercharger Ready',
    },
    features: [
      'Full Self-Driving',
      'Long Range Battery',
      'Premium Interior',
      'Charging Included',
      'Warranty Transferable',
    ],
    inStock: true,
    seller: {
      name: 'Electric Vehicle Pro',
      avatar: 'https://i.pravatar.cc/150?img=88',
      rating: 4.8,
      reviews: 267,
      verified: true,
    },
  },
  // Additional Electronics (4 more to reach 10)
  {
    id: 'm21',
    title: '4K Smart TV 55"',
    name: '4K Smart TV 55"',
    price: 49900,
    originalPrice: 69900,
    image: 'https://images.unsplash.com/photo-1593359677879-a4b92a0a4c6a?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 523,
    category: 'Electronics',
    location: 'Chicago, IL',
    description: 'Ultra HD 4K Smart TV with HDR, voice control, and streaming apps. Features Dolby Vision, built-in Wi-Fi, and multiple HDMI ports.',
    specifications: {
      'Screen Size': '55 inches',
      'Resolution': '4K UHD (3840x2160)',
      'Smart Platform': 'Android TV',
      'HDR': 'Dolby Vision & HDR10',
      'Connectivity': 'Wi-Fi, Bluetooth, HDMI x4',
    },
    features: [
      '4K Ultra HD Display',
      'Smart TV Features',
      'Dolby Vision HDR',
      'Voice Control',
      'Multiple Streaming Apps',
    ],
    inStock: true,
    seller: {
      name: 'Home Entertainment Plus',
      avatar: 'https://i.pravatar.cc/150?img=13',
      rating: 4.8,
      reviews: 789,
      verified: true,
    },
  },
  {
    id: 'm22',
    title: 'Tablet Pro 12.9"',
    name: 'Tablet Pro 12.9"',
    price: 89900,
    originalPrice: 109900,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 412,
    category: 'Electronics',
    location: 'Austin, TX',
    description: 'Professional tablet with 12.9-inch display, powerful processor, and Apple Pencil support. Perfect for creative professionals and productivity.',
    specifications: {
      'Display': '12.9" Liquid Retina',
      'Storage': '256GB',
      'RAM': '8GB',
      'Processor': 'M2 Chip',
      'Battery': 'Up to 10 hours',
    },
    features: [
      'Apple Pencil Compatible',
      'Magic Keyboard Ready',
      'Face ID',
      '5G Connectivity',
      'Professional Apps',
    ],
    inStock: true,
    seller: {
      name: 'Tech Pro Store',
      avatar: 'https://i.pravatar.cc/150?img=14',
      rating: 4.9,
      reviews: 1023,
      verified: true,
    },
  },
  {
    id: 'm23',
    title: 'Smart Speaker with Alexa',
    name: 'Smart Speaker with Alexa',
    price: 9999,
    originalPrice: 14999,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 678,
    category: 'Electronics',
    location: 'Portland, OR',
    description: 'Premium smart speaker with Alexa voice assistant, 360-degree sound, and smart home control. Perfect for music, news, and home automation.',
    specifications: {
      'Audio': '360° Sound',
      'Voice Assistant': 'Alexa',
      'Connectivity': 'Wi-Fi, Bluetooth',
      'Smart Home': 'Compatible',
      'Battery': 'Plug-in',
    },
    features: [
      'Alexa Voice Control',
      '360° Sound',
      'Smart Home Hub',
      'Multi-room Audio',
      'Music Streaming',
    ],
    inStock: true,
    seller: {
      name: 'Smart Home Solutions',
      avatar: 'https://i.pravatar.cc/150?img=15',
      rating: 4.7,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm24',
    title: 'Digital Camera Pro',
    name: 'Digital Camera Pro',
    price: 129900,
    originalPrice: 159900,
    image: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 234,
    category: 'Electronics',
    location: 'Denver, CO',
    description: 'Professional mirrorless camera with 24MP sensor, 4K video, and interchangeable lens system. Perfect for photography enthusiasts.',
    specifications: {
      'Sensor': '24MP Full Frame',
      'Video': '4K at 60fps',
      'ISO Range': '100-51200',
      'Lens Mount': 'Interchangeable',
      'Battery': 'Up to 530 shots',
    },
    features: [
      '4K Video Recording',
      'Fast Autofocus',
      'Image Stabilization',
      'Wi-Fi & Bluetooth',
      'Weather Sealed',
    ],
    inStock: true,
    seller: {
      name: 'Camera World',
      avatar: 'https://i.pravatar.cc/150?img=16',
      rating: 4.9,
      reviews: 567,
      verified: true,
    },
  },
  // Additional Apparel (5 more to reach 10)
  {
    id: 'm25',
    title: 'Winter Jacket Premium',
    name: 'Winter Jacket Premium',
    price: 17900,
    originalPrice: 24900,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 345,
    category: 'Apparel',
    location: 'Minneapolis, MN',
    description: 'Premium winter jacket with down insulation, waterproof exterior, and adjustable hood. Perfect for cold weather adventures.',
    specifications: {
      'Material': 'Nylon & Down',
      'Insulation': '600 Fill Power',
      'Waterproof': 'Yes',
      'Sizes': 'XS, S, M, L, XL, XXL',
      'Colors': 'Black, Navy, Gray',
    },
    features: [
      'Down Insulation',
      'Waterproof',
      'Adjustable Hood',
      'Multiple Pockets',
      'Wind Resistant',
    ],
    inStock: true,
    seller: {
      name: 'Outdoor Gear Co',
      avatar: 'https://i.pravatar.cc/150?img=17',
      rating: 4.8,
      reviews: 678,
      verified: true,
    },
  },
  {
    id: 'm26',
    title: 'Designer Handbag',
    name: 'Designer Handbag',
    price: 34900,
    originalPrice: 49900,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 567,
    category: 'Apparel',
    location: 'Paris, France',
    description: 'Luxury designer handbag crafted from premium leather with gold hardware. Spacious interior, adjustable strap, and elegant design.',
    specifications: {
      'Material': 'Genuine Leather',
      'Dimensions': '12" x 9" x 5"',
      'Hardware': 'Gold Plated',
      'Interior': 'Lined',
      'Style': 'Crossbody & Shoulder',
    },
    features: [
      'Premium Leather',
      'Gold Hardware',
      'Adjustable Strap',
      'Multiple Compartments',
      'Authenticity Card',
    ],
    inStock: true,
    seller: {
      name: 'Luxury Fashion House',
      avatar: 'https://i.pravatar.cc/150?img=18',
      rating: 4.9,
      reviews: 890,
      verified: true,
    },
  },
  {
    id: 'm27',
    title: 'Athletic Shorts Pack',
    name: 'Athletic Shorts Pack',
    price: 2999,
    originalPrice: 4999,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&h=800&fit=crop',
    rating: 4.5,
    reviews: 234,
    category: 'Apparel',
    location: 'Phoenix, AZ',
    description: 'Pack of 3 athletic shorts with moisture-wicking fabric, elastic waistband, and breathable design. Perfect for workouts and sports.',
    specifications: {
      'Material': 'Polyester Blend',
      'Pack Size': '3 Shorts',
      'Sizes': 'S, M, L, XL',
      'Features': 'Moisture Wicking',
      'Colors': 'Black, Gray, Navy',
    },
    features: [
      'Moisture Wicking',
      'Elastic Waistband',
      'Breathable Fabric',
      'Pack of 3',
      'Machine Washable',
    ],
    inStock: true,
    seller: {
      name: 'Active Wear Store',
      avatar: 'https://i.pravatar.cc/150?img=19',
      rating: 4.6,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm28',
    title: 'Silk Scarf Collection',
    name: 'Silk Scarf Collection',
    price: 8900,
    originalPrice: 12900,
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 189,
    category: 'Apparel',
    location: 'Milan, Italy',
    description: 'Luxury silk scarves in various patterns and colors. Hand-rolled edges, premium quality, and versatile styling options.',
    specifications: {
      'Material': '100% Silk',
      'Dimensions': '35" x 35"',
      'Collection': '3 Scarves',
      'Care': 'Dry Clean Only',
      'Patterns': 'Floral, Geometric, Abstract',
    },
    features: [
      '100% Pure Silk',
      'Hand-rolled Edges',
      'Multiple Patterns',
      'Gift Box Included',
      'Versatile Styling',
    ],
    inStock: true,
    seller: {
      name: 'Silk Elegance',
      avatar: 'https://i.pravatar.cc/150?img=20',
      rating: 4.8,
      reviews: 345,
      verified: true,
    },
  },
  {
    id: 'm29',
    title: 'Denim Jeans Classic',
    name: 'Denim Jeans Classic',
    price: 7900,
    originalPrice: 11900,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 456,
    category: 'Apparel',
    location: 'Dallas, TX',
    description: 'Classic fit denim jeans with stretch comfort, durable construction, and timeless style. Available in multiple washes and sizes.',
    specifications: {
      'Material': '98% Cotton, 2% Elastane',
      'Fit': 'Classic',
      'Sizes': '28-38',
      'Washes': 'Light, Medium, Dark',
      'Rise': 'Mid Rise',
    },
    features: [
      'Stretch Comfort',
      'Durable Construction',
      'Classic Fit',
      'Multiple Washes',
      'Timeless Style',
    ],
    inStock: true,
    seller: {
      name: 'Denim Co',
      avatar: 'https://i.pravatar.cc/150?img=21',
      rating: 4.7,
      reviews: 678,
      verified: true,
    },
  },
  // Additional Real Estate (8 more to reach 10)
  {
    id: 'm30',
    title: 'Downtown Studio Apartment',
    name: 'Downtown Studio Apartment',
    price: 18000000,
    originalPrice: 20000000,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 38,
    category: 'Real Estate',
    location: 'Chicago, IL',
    description: 'Modern studio apartment in downtown area. Open floor plan, high ceilings, and city views. Perfect for young professionals.',
    specifications: {
      'Bedrooms': 'Studio',
      'Bathrooms': '1',
      'Square Feet': '650 sq ft',
      'Year Built': '2019',
      'Parking': 'Street Parking',
    },
    features: [
      'Open Floor Plan',
      'High Ceilings',
      'City Views',
      'Modern Appliances',
      'Pet Friendly',
    ],
    inStock: true,
    seller: {
      name: 'Urban Living Realty',
      avatar: 'https://i.pravatar.cc/150?img=23',
      rating: 4.7,
      reviews: 145,
      verified: true,
    },
  },
  {
    id: 'm31',
    title: 'Suburban Family Home',
    name: 'Suburban Family Home',
    price: 45000000,
    originalPrice: 50000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 42,
    category: 'Real Estate',
    location: 'Austin, TX',
    description: 'Spacious 3-bedroom family home in quiet neighborhood. Large backyard, 2-car garage, and excellent schools nearby.',
    specifications: {
      'Bedrooms': '3',
      'Bathrooms': '2.5',
      'Square Feet': '2,200 sq ft',
      'Year Built': '2015',
      'Lot Size': '0.25 acres',
    },
    features: [
      'Large Backyard',
      '2-Car Garage',
      'Updated Kitchen',
      'Hardwood Floors',
      'Great Schools',
    ],
    inStock: true,
    seller: {
      name: 'Family Homes Realty',
      avatar: 'https://i.pravatar.cc/150?img=24',
      rating: 4.8,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm32',
    title: 'Beachfront Condo',
    name: 'Beachfront Condo',
    price: 65000000,
    originalPrice: 75000000,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 28,
    category: 'Real Estate',
    location: 'Miami, FL',
    description: 'Luxury beachfront condo with ocean views, balcony, and resort amenities. Pool, gym, and beach access included.',
    specifications: {
      'Bedrooms': '2',
      'Bathrooms': '2',
      'Square Feet': '1,400 sq ft',
      'Year Built': '2021',
      'Parking': '1 Space',
    },
    features: [
      'Ocean Views',
      'Private Balcony',
      'Resort Amenities',
      'Pool Access',
      'Beach Access',
    ],
    inStock: true,
    seller: {
      name: 'Beach Properties',
      avatar: 'https://i.pravatar.cc/150?img=25',
      rating: 4.9,
      reviews: 189,
      verified: true,
    },
  },
  {
    id: 'm33',
    title: 'Penthouse Apartment',
    name: 'Penthouse Apartment',
    price: 120000000,
    originalPrice: 140000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 15,
    category: 'Real Estate',
    location: 'New York, NY',
    description: 'Stunning penthouse with panoramic city views, private terrace, and luxury finishes. High-end appliances and smart home features.',
    specifications: {
      'Bedrooms': '3',
      'Bathrooms': '3.5',
      'Square Feet': '3,200 sq ft',
      'Year Built': '2022',
      'Parking': '2 Spaces',
    },
    features: [
      'Panoramic Views',
      'Private Terrace',
      'Luxury Finishes',
      'Smart Home',
      'Concierge Service',
    ],
    inStock: true,
    seller: {
      name: 'Luxury Estates',
      avatar: 'https://i.pravatar.cc/150?img=26',
      rating: 4.9,
      reviews: 78,
      verified: true,
    },
  },
  {
    id: 'm34',
    title: 'Countryside Villa',
    name: 'Countryside Villa',
    price: 95000000,
    originalPrice: 110000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 22,
    category: 'Real Estate',
    location: 'Napa Valley, CA',
    description: 'Beautiful countryside villa with vineyard views, pool, and extensive gardens. Perfect for wine enthusiasts and nature lovers.',
    specifications: {
      'Bedrooms': '5',
      'Bathrooms': '4',
      'Square Feet': '4,500 sq ft',
      'Year Built': '2010',
      'Lot Size': '2 acres',
    },
    features: [
      'Vineyard Views',
      'Swimming Pool',
      'Extensive Gardens',
      'Wine Cellar',
      'Guest House',
    ],
    inStock: true,
    seller: {
      name: 'Estate Properties',
      avatar: 'https://i.pravatar.cc/150?img=27',
      rating: 4.8,
      reviews: 112,
      verified: true,
    },
  },
  {
    id: 'm35',
    title: 'Townhouse Modern',
    name: 'Townhouse Modern',
    price: 32000000,
    originalPrice: 36000000,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 35,
    category: 'Real Estate',
    location: 'Seattle, WA',
    description: 'Modern 3-story townhouse with rooftop deck, updated kitchen, and contemporary design. Located in trendy neighborhood.',
    specifications: {
      'Bedrooms': '3',
      'Bathrooms': '2.5',
      'Square Feet': '1,800 sq ft',
      'Year Built': '2018',
      'Parking': '1 Space',
    },
    features: [
      'Rooftop Deck',
      'Updated Kitchen',
      'Modern Design',
      'Hardwood Floors',
      'Walkable Neighborhood',
    ],
    inStock: true,
    seller: {
      name: 'Modern Living Realty',
      avatar: 'https://i.pravatar.cc/150?img=28',
      rating: 4.7,
      reviews: 167,
      verified: true,
    },
  },
  {
    id: 'm36',
    title: 'Luxury Waterfront Estate',
    name: 'Luxury Waterfront Estate',
    price: 150000000,
    originalPrice: 175000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 12,
    category: 'Real Estate',
    location: 'Malibu, CA',
    description: 'Exclusive waterfront estate with private beach, infinity pool, and luxury amenities. Stunning ocean views and privacy.',
    specifications: {
      'Bedrooms': '6',
      'Bathrooms': '7',
      'Square Feet': '8,500 sq ft',
      'Year Built': '2019',
      'Lot Size': '1.5 acres',
    },
    features: [
      'Private Beach',
      'Infinity Pool',
      'Ocean Views',
      'Home Theater',
      'Wine Cellar',
    ],
    inStock: true,
    seller: {
      name: 'Exclusive Properties',
      avatar: 'https://i.pravatar.cc/150?img=29',
      rating: 4.9,
      reviews: 45,
      verified: true,
    },
  },
  {
    id: 'm37',
    title: 'Historic Brownstone',
    name: 'Historic Brownstone',
    price: 55000000,
    originalPrice: 65000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 19,
    category: 'Real Estate',
    location: 'Boston, MA',
    description: 'Beautifully restored historic brownstone with original details, modern updates, and prime location. Character and charm throughout.',
    specifications: {
      'Bedrooms': '4',
      'Bathrooms': '3',
      'Square Feet': '3,000 sq ft',
      'Year Built': '1895',
      'Parking': 'Street Parking',
    },
    features: [
      'Historic Character',
      'Original Details',
      'Modern Updates',
      'Prime Location',
      'Restored',
    ],
    inStock: true,
    seller: {
      name: 'Historic Homes',
      avatar: 'https://i.pravatar.cc/150?img=30',
      rating: 4.8,
      reviews: 89,
      verified: true,
    },
  },
  // Additional Jobs (8 more to reach 10)
  {
    id: 'm38',
    title: 'Product Manager Role',
    name: 'Product Manager Role',
    price: 130000,
    originalPrice: 150000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 34,
    category: 'Jobs',
    location: 'San Francisco, CA',
    description: 'Senior product manager position at fast-growing tech company. Lead product strategy, work with engineering teams, and drive innovation.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '5+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Full Package',
      'Salary Range': '$130k - $150k',
    },
    features: [
      'Product Strategy',
      'Team Leadership',
      'Competitive Salary',
      'Stock Options',
      'Career Growth',
    ],
    inStock: true,
    seller: {
      name: 'Tech Startup Inc',
      avatar: 'https://i.pravatar.cc/150?img=31',
      rating: 4.8,
      reviews: 123,
      verified: true,
    },
  },
  {
    id: 'm39',
    title: 'Graphic Designer Position',
    name: 'Graphic Designer Position',
    price: 65000,
    originalPrice: 75000,
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 27,
    category: 'Jobs',
    location: 'Los Angeles, CA',
    description: 'Creative graphic designer role for digital agency. Work on diverse projects, collaborate with creative team, and develop visual concepts.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '2+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Health, Dental',
      'Salary Range': '$65k - $75k',
    },
    features: [
      'Creative Projects',
      'Team Collaboration',
      'Portfolio Building',
      'Flexible Hours',
      'Professional Development',
    ],
    inStock: true,
    seller: {
      name: 'Creative Digital Agency',
      avatar: 'https://i.pravatar.cc/150?img=32',
      rating: 4.7,
      reviews: 98,
      verified: true,
    },
  },
  {
    id: 'm40',
    title: 'Data Scientist Role',
    name: 'Data Scientist Role',
    price: 140000,
    originalPrice: 165000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 41,
    category: 'Jobs',
    location: 'Boston, MA',
    description: 'Senior data scientist position working with machine learning, big data, and analytics. Build predictive models and insights.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '4+ years',
      'Remote': 'Yes',
      'Benefits': 'Full Package',
      'Salary Range': '$140k - $165k',
    },
    features: [
      'Machine Learning',
      'Big Data Projects',
      'Remote Work',
      'Research Opportunities',
      'Competitive Benefits',
    ],
    inStock: true,
    seller: {
      name: 'Data Analytics Corp',
      avatar: 'https://i.pravatar.cc/150?img=33',
      rating: 4.8,
      reviews: 156,
      verified: true,
    },
  },
  {
    id: 'm41',
    title: 'UX Designer Position',
    name: 'UX Designer Position',
    price: 95000,
    originalPrice: 110000,
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 33,
    category: 'Jobs',
    location: 'Seattle, WA',
    description: 'UX designer role focusing on user research, wireframing, and prototyping. Work with cross-functional teams to create user-centered designs.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '3+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Full Package',
      'Salary Range': '$95k - $110k',
    },
    features: [
      'User Research',
      'Design Systems',
      'Prototyping Tools',
      'Team Collaboration',
      'Portfolio Growth',
    ],
    inStock: true,
    seller: {
      name: 'Design Innovation Lab',
      avatar: 'https://i.pravatar.cc/150?img=34',
      rating: 4.8,
      reviews: 112,
      verified: true,
    },
  },
  {
    id: 'm42',
    title: 'Sales Manager Position',
    name: 'Sales Manager Position',
    price: 85000,
    originalPrice: 100000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.6,
    reviews: 29,
    category: 'Jobs',
    location: 'Chicago, IL',
    description: 'Sales manager role leading sales team, developing strategies, and driving revenue growth. Commission-based with excellent earning potential.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '3+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Health, Commission',
      'Salary Range': '$85k - $100k + Commission',
    },
    features: [
      'Team Leadership',
      'Commission Based',
      'Growth Opportunities',
      'Sales Training',
      'Performance Bonuses',
    ],
    inStock: true,
    seller: {
      name: 'Sales Solutions Inc',
      avatar: 'https://i.pravatar.cc/150?img=35',
      rating: 4.7,
      reviews: 145,
      verified: true,
    },
  },
  {
    id: 'm43',
    title: 'DevOps Engineer Role',
    name: 'DevOps Engineer Role',
    price: 120000,
    originalPrice: 140000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 38,
    category: 'Jobs',
    location: 'Austin, TX',
    description: 'DevOps engineer position managing cloud infrastructure, CI/CD pipelines, and automation. Work with modern tools and technologies.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '4+ years',
      'Remote': 'Yes',
      'Benefits': 'Full Package',
      'Salary Range': '$120k - $140k',
    },
    features: [
      'Cloud Infrastructure',
      'CI/CD Pipelines',
      'Automation Tools',
      'Remote Work',
      'Tech Stack Growth',
    ],
    inStock: true,
    seller: {
      name: 'Cloud Tech Solutions',
      avatar: 'https://i.pravatar.cc/150?img=36',
      rating: 4.8,
      reviews: 189,
      verified: true,
    },
  },
  {
    id: 'm44',
    title: 'Content Writer Position',
    name: 'Content Writer Position',
    price: 55000,
    originalPrice: 65000,
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=800&fit=crop',
    rating: 4.5,
    reviews: 24,
    category: 'Jobs',
    location: 'Remote',
    description: 'Content writer role creating blog posts, articles, and marketing copy. Remote position with flexible schedule and creative freedom.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '2+ years',
      'Remote': 'Yes',
      'Benefits': 'Health, Dental',
      'Salary Range': '$55k - $65k',
    },
    features: [
      'Remote Work',
      'Flexible Schedule',
      'Creative Freedom',
      'Diverse Topics',
      'Portfolio Building',
    ],
    inStock: true,
    seller: {
      name: 'Content Marketing Co',
      avatar: 'https://i.pravatar.cc/150?img=37',
      rating: 4.6,
      reviews: 78,
      verified: true,
    },
  },
  {
    id: 'm45',
    title: 'Financial Analyst Role',
    name: 'Financial Analyst Role',
    price: 75000,
    originalPrice: 90000,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 31,
    category: 'Jobs',
    location: 'New York, NY',
    description: 'Financial analyst position analyzing market trends, preparing reports, and supporting investment decisions. Great for career advancement.',
    specifications: {
      'Type': 'Full-time',
      'Experience': '2+ years',
      'Remote': 'Hybrid',
      'Benefits': 'Full Package',
      'Salary Range': '$75k - $90k',
    },
    features: [
      'Market Analysis',
      'Financial Modeling',
      'Career Growth',
      'Professional Development',
      'Competitive Benefits',
    ],
    inStock: true,
    seller: {
      name: 'Finance Group LLC',
      avatar: 'https://i.pravatar.cc/150?img=38',
      rating: 4.7,
      reviews: 134,
      verified: true,
    },
  },
  // Additional Services (8 more to reach 10)
  {
    id: 'm46',
    title: 'Logo Design Package',
    name: 'Logo Design Package',
    price: 500,
    originalPrice: 800,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 567,
    category: 'Services',
    location: 'Remote',
    description: 'Professional logo design package including 3 concepts, unlimited revisions, and multiple file formats. Perfect for startups and businesses.',
    specifications: {
      'Delivery Time': '3-5 days',
      'Concepts': '3 Initial',
      'Revisions': 'Unlimited',
      'File Formats': 'All Formats',
      'Support': '1 month',
    },
    features: [
      '3 Logo Concepts',
      'Unlimited Revisions',
      'Multiple Formats',
      'Brand Guidelines',
      'Commercial License',
    ],
    inStock: true,
    seller: {
      name: 'Brand Design Studio',
      avatar: 'https://i.pravatar.cc/150?img=39',
      rating: 4.9,
      reviews: 789,
      verified: true,
    },
  },
  {
    id: 'm47',
    title: 'SEO Optimization Service',
    name: 'SEO Optimization Service',
    price: 1200,
    originalPrice: 1800,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 234,
    category: 'Services',
    location: 'Remote',
    description: 'Comprehensive SEO optimization including keyword research, on-page optimization, technical SEO, and monthly reporting.',
    specifications: {
      'Duration': '3 months',
      'Keywords': 'Up to 20',
      'Reports': 'Monthly',
      'Support': 'Email & Phone',
      'Guarantee': 'Results Focused',
    },
    features: [
      'Keyword Research',
      'On-Page SEO',
      'Technical SEO',
      'Monthly Reports',
      'Performance Tracking',
    ],
    inStock: true,
    seller: {
      name: 'SEO Experts Pro',
      avatar: 'https://i.pravatar.cc/150?img=40',
      rating: 4.8,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm48',
    title: 'Video Editing Service',
    name: 'Video Editing Service',
    price: 800,
    originalPrice: 1200,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 345,
    category: 'Services',
    location: 'Remote',
    description: 'Professional video editing service for promotional videos, social media content, and marketing materials. Fast turnaround and high quality.',
    specifications: {
      'Delivery Time': '2-3 days',
      'Video Length': 'Up to 5 minutes',
      'Revisions': '2 Rounds',
      'Format': 'All Formats',
      'Music': 'Royalty Free',
    },
    features: [
      'Professional Editing',
      'Color Grading',
      'Motion Graphics',
      'Sound Design',
      'Fast Delivery',
    ],
    inStock: true,
    seller: {
      name: 'Video Production Co',
      avatar: 'https://i.pravatar.cc/150?img=41',
      rating: 4.8,
      reviews: 567,
      verified: true,
    },
  },
  {
    id: 'm49',
    title: 'Social Media Management',
    name: 'Social Media Management',
    price: 2000,
    originalPrice: 2800,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 189,
    category: 'Services',
    location: 'Remote',
    description: 'Complete social media management for 3 platforms including content creation, posting schedule, engagement, and analytics.',
    specifications: {
      'Duration': '1 month',
      'Platforms': '3 Platforms',
      'Posts': '20 per month',
      'Engagement': 'Daily',
      'Reports': 'Weekly',
    },
    features: [
      'Content Creation',
      'Posting Schedule',
      'Community Management',
      'Analytics Reports',
      'Strategy Development',
    ],
    inStock: true,
    seller: {
      name: 'Social Media Pro',
      avatar: 'https://i.pravatar.cc/150?img=42',
      rating: 4.8,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm50',
    title: 'Photography Services',
    name: 'Photography Services',
    price: 1500,
    originalPrice: 2200,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 456,
    category: 'Services',
    location: 'Los Angeles, CA',
    description: 'Professional photography services for events, portraits, products, and commercial work. High-quality images with editing included.',
    specifications: {
      'Session Duration': '2-4 hours',
      'Images': '50+ Edited',
      'Delivery': '1-2 weeks',
      'Format': 'High Resolution',
      'Usage Rights': 'Commercial',
    },
    features: [
      'Professional Equipment',
      'Expert Editing',
      'High Resolution',
      'Multiple Shots',
      'Commercial License',
    ],
    inStock: true,
    seller: {
      name: 'Pro Photography Studio',
      avatar: 'https://i.pravatar.cc/150?img=43',
      rating: 4.9,
      reviews: 678,
      verified: true,
    },
  },
  {
    id: 'm51',
    title: 'App Development Service',
    name: 'App Development Service',
    price: 5000,
    originalPrice: 7500,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 123,
    category: 'Services',
    location: 'Remote',
    description: 'Custom mobile app development for iOS and Android. Includes design, development, testing, and app store submission.',
    specifications: {
      'Delivery Time': '6-8 weeks',
      'Platforms': 'iOS & Android',
      'Revisions': '3 Rounds',
      'Support': '3 months',
      'Updates': 'Included',
    },
    features: [
      'Custom Design',
      'Native Development',
      'App Store Submission',
      'Testing & QA',
      'Ongoing Support',
    ],
    inStock: true,
    seller: {
      name: 'Mobile App Developers',
      avatar: 'https://i.pravatar.cc/150?img=44',
      rating: 4.8,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm52',
    title: 'Copywriting Service',
    name: 'Copywriting Service',
    price: 600,
    originalPrice: 900,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 278,
    category: 'Services',
    location: 'Remote',
    description: 'Professional copywriting for websites, marketing materials, and advertising. SEO-optimized, engaging, and conversion-focused content.',
    specifications: {
      'Delivery Time': '3-5 days',
      'Word Count': 'Up to 2000',
      'Revisions': '2 Rounds',
      'SEO': 'Included',
      'Format': 'Any Format',
    },
    features: [
      'SEO Optimized',
      'Conversion Focused',
      'Multiple Formats',
      'Fast Delivery',
      'Unlimited Revisions',
    ],
    inStock: true,
    seller: {
      name: 'Copywriting Experts',
      avatar: 'https://i.pravatar.cc/150?img=45',
      rating: 4.8,
      reviews: 345,
      verified: true,
    },
  },
  {
    id: 'm53',
    title: 'E-commerce Setup Service',
    name: 'E-commerce Setup Service',
    price: 1800,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 167,
    category: 'Services',
    location: 'Remote',
    description: 'Complete e-commerce store setup including platform selection, design, product setup, payment integration, and training.',
    specifications: {
      'Delivery Time': '2-3 weeks',
      'Platform': 'Shopify/WooCommerce',
      'Products': 'Up to 50',
      'Training': 'Included',
      'Support': '1 month',
    },
    features: [
      'Store Setup',
      'Payment Integration',
      'Product Management',
      'Training Provided',
      'Ongoing Support',
    ],
    inStock: true,
    seller: {
      name: 'E-commerce Solutions',
      avatar: 'https://i.pravatar.cc/150?img=46',
      rating: 4.8,
      reviews: 289,
      verified: true,
    },
  },
  // Additional Vehicles (8 more to reach 10)
  {
    id: 'm54',
    title: '2022 Honda Civic',
    name: '2022 Honda Civic',
    price: 2800000,
    originalPrice: 3200000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 156,
    category: 'Vehicles',
    location: 'Atlanta, GA',
    description: 'Reliable 2022 Honda Civic with low mileage, excellent fuel economy, and modern features. Well-maintained, single owner, clean history.',
    specifications: {
      'Year': '2022',
      'Mileage': '15,000 miles',
      'Engine': '1.5L Turbo',
      'Transmission': 'CVT',
      'Fuel': 'Gasoline',
    },
    features: [
      'Low Mileage',
      'Great Fuel Economy',
      'Modern Features',
      'Clean History',
      'Well Maintained',
    ],
    inStock: true,
    seller: {
      name: 'Reliable Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=47',
      rating: 4.7,
      reviews: 456,
      verified: true,
    },
  },
  {
    id: 'm55',
    title: '2021 Ford F-150',
    name: '2021 Ford F-150',
    price: 4200000,
    originalPrice: 4800000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 189,
    category: 'Vehicles',
    location: 'Dallas, TX',
    description: 'Powerful 2021 Ford F-150 pickup truck with towing package, 4WD, and premium features. Perfect for work and adventure.',
    specifications: {
      'Year': '2021',
      'Mileage': '22,000 miles',
      'Engine': '3.5L V6 EcoBoost',
      'Transmission': '10-Speed Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      'Towing Package',
      '4WD Capability',
      'Premium Interior',
      'Advanced Safety',
      'Well Maintained',
    ],
    inStock: true,
    seller: {
      name: 'Truck Specialists',
      avatar: 'https://i.pravatar.cc/150?img=48',
      rating: 4.8,
      reviews: 567,
      verified: true,
    },
  },
  {
    id: 'm56',
    title: '2023 Mercedes-Benz C-Class',
    name: '2023 Mercedes-Benz C-Class',
    price: 4800000,
    originalPrice: 5500000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.9,
    reviews: 98,
    category: 'Vehicles',
    location: 'Miami, FL',
    description: 'Luxury 2023 Mercedes-Benz C-Class with premium features, advanced technology, and elegant design. Low mileage, like new condition.',
    specifications: {
      'Year': '2023',
      'Mileage': '5,000 miles',
      'Engine': '2.0L Turbo',
      'Transmission': '9-Speed Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      'Premium Interior',
      'Advanced Technology',
      'Safety Features',
      'Low Mileage',
      'Warranty Included',
    ],
    inStock: true,
    seller: {
      name: 'Luxury Auto Gallery',
      avatar: 'https://i.pravatar.cc/150?img=49',
      rating: 4.9,
      reviews: 234,
      verified: true,
    },
  },
  {
    id: 'm57',
    title: '2022 Toyota Camry Hybrid',
    name: '2022 Toyota Camry Hybrid',
    price: 3200000,
    originalPrice: 3800000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 234,
    category: 'Vehicles',
    location: 'Portland, OR',
    description: 'Efficient 2022 Toyota Camry Hybrid with excellent fuel economy, reliable performance, and modern safety features. Perfect for daily commute.',
    specifications: {
      'Year': '2022',
      'Mileage': '18,000 miles',
      'Engine': '2.5L Hybrid',
      'Transmission': 'CVT',
      'Fuel': 'Hybrid',
    },
    features: [
      'Excellent MPG',
      'Hybrid Technology',
      'Safety Features',
      'Reliable Performance',
      'Clean History',
    ],
    inStock: true,
    seller: {
      name: 'Eco Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=50',
      rating: 4.8,
      reviews: 345,
      verified: true,
    },
  },
  {
    id: 'm58',
    title: '2021 Jeep Wrangler',
    name: '2021 Jeep Wrangler',
    price: 3800000,
    originalPrice: 4500000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 167,
    category: 'Vehicles',
    location: 'Denver, CO',
    description: 'Adventure-ready 2021 Jeep Wrangler with 4WD, removable doors, and off-road capabilities. Perfect for outdoor enthusiasts.',
    specifications: {
      'Year': '2021',
      'Mileage': '25,000 miles',
      'Engine': '3.6L V6',
      'Transmission': '8-Speed Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      '4WD Capability',
      'Removable Doors',
      'Off-Road Ready',
      'Adventure Features',
      'Well Maintained',
    ],
    inStock: true,
    seller: {
      name: 'Adventure Vehicles',
      avatar: 'https://i.pravatar.cc/150?img=51',
      rating: 4.8,
      reviews: 278,
      verified: true,
    },
  },
  {
    id: 'm59',
    title: '2023 Audi A4',
    name: '2023 Audi A4',
    price: 4500000,
    originalPrice: 5200000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.8,
    reviews: 112,
    category: 'Vehicles',
    location: 'San Diego, CA',
    description: 'Sophisticated 2023 Audi A4 with quattro AWD, premium interior, and advanced technology. Low mileage, excellent condition.',
    specifications: {
      'Year': '2023',
      'Mileage': '8,000 miles',
      'Engine': '2.0L Turbo',
      'Transmission': '7-Speed Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      'Quattro AWD',
      'Premium Interior',
      'Advanced Tech',
      'Low Mileage',
      'Warranty Transferable',
    ],
    inStock: true,
    seller: {
      name: 'Premium Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=52',
      rating: 4.9,
      reviews: 189,
      verified: true,
    },
  },
  {
    id: 'm60',
    title: '2022 Subaru Outback',
    name: '2022 Subaru Outback',
    price: 3500000,
    originalPrice: 4100000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 198,
    category: 'Vehicles',
    location: 'Seattle, WA',
    description: 'Versatile 2022 Subaru Outback with all-wheel drive, spacious interior, and safety features. Perfect for families and outdoor activities.',
    specifications: {
      'Year': '2022',
      'Mileage': '20,000 miles',
      'Engine': '2.5L Boxer',
      'Transmission': 'CVT',
      'Fuel': 'Gasoline',
    },
    features: [
      'All-Wheel Drive',
      'Spacious Interior',
      'Safety Features',
      'Roof Rails',
      'Family Friendly',
    ],
    inStock: true,
    seller: {
      name: 'Family Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=53',
      rating: 4.8,
      reviews: 312,
      verified: true,
    },
  },
  {
    id: 'm61',
    title: '2021 Chevrolet Silverado',
    name: '2021 Chevrolet Silverado',
    price: 4000000,
    originalPrice: 4700000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=800&fit=crop',
    rating: 4.7,
    reviews: 145,
    category: 'Vehicles',
    location: 'Houston, TX',
    description: 'Powerful 2021 Chevrolet Silverado with towing capacity, crew cab, and modern technology. Great for work and family use.',
    specifications: {
      'Year': '2021',
      'Mileage': '28,000 miles',
      'Engine': '5.3L V8',
      'Transmission': '8-Speed Automatic',
      'Fuel': 'Gasoline',
    },
    features: [
      'Towing Capacity',
      'Crew Cab',
      'Modern Technology',
      'Work Ready',
      'Well Maintained',
    ],
    inStock: true,
    seller: {
      name: 'Truck & Auto Sales',
      avatar: 'https://i.pravatar.cc/150?img=54',
      rating: 4.7,
      reviews: 234,
      verified: true,
    },
  },
];

