export const MINT_SERVICES = [
  {
    id: 'handyman',
    name: 'MINT Handyman',
    description: 'Reliable help for home repairs.',
    icon: 'hammer-wrench',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=640&h=480&fit=crop',
    price: '$89',
    location: 'Springdale Heights',
    isPopular: true,
    isFavorite: false,
  },
  {
    id: 'market',
    name: 'MINT Market',
    description: 'Groceries and goods delivered fast.',
    icon: 'shopping-outline',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=640&h=480&fit=crop',
    price: '$45',
    location: 'Downtown Plaza',
    isPopular: true,
    isFavorite: true,
  },
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Latest gadgets and tech devices.',
    icon: 'laptop',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=640&h=480&fit=crop',
    price: '$299',
    location: 'Tech Plaza',
    isPopular: true,
    isFavorite: false,
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    description: 'Find your dream home.',
    icon: 'home-city',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=640&h=480&fit=crop',
    price: '$2,700,000',
    location: 'Springdale Heights',
    isPopular: true,
    isFavorite: true,
  },
  {
    id: 'jobs',
    name: 'Jobs',
    description: 'Career opportunities near you.',
    icon: 'briefcase',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=640&h=480&fit=crop',
    price: '$65k',
    location: 'Business District',
    isPopular: false,
    isFavorite: false,
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    description: 'Cars, bikes, and more.',
    icon: 'car',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=640&h=480&fit=crop',
    price: '$25,000',
    location: 'Auto Mall',
    isPopular: true,
    isFavorite: false,
  },
  {
    id: 'ride',
    name: 'MINT Ride',
    description: 'Get a ride in minutes.',
    icon: 'car',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=640&h=480&fit=crop',
    price: '$25',
    location: 'City Center',
    isPopular: false,
    isFavorite: false,
  },
  {
    id: 'deliver',
    name: 'MINT Deliver',
    description: 'Send packages across the city.',
    icon: 'truck-delivery',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=640&h=480&fit=crop',
    price: '$35',
    location: 'Metro District',
    isPopular: true,
    isFavorite: false,
  },
  {
    id: 'park',
    name: 'MINT Park',
    description: 'Find and reserve parking spots.',
    icon: 'parking',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1509824227185-9c5a01ceba0d?w=640&h=480&fit=crop',
    price: '$12',
    location: 'Central Station',
    isPopular: false,
    isFavorite: true,
  },
  {
    id: 'furniture',
    name: 'Furniture',
    description: 'Home and office furniture.',
    icon: 'sofa',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=640&h=480&fit=crop',
    price: '$450',
    location: 'Furniture Row',
    isPopular: false,
    isFavorite: false,
  },
  {
    id: 'clothing',
    name: 'Clothing',
    description: 'Fashion and apparel.',
    icon: 'tshirt-crew',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=640&h=480&fit=crop',
    price: '$89',
    location: 'Fashion District',
    isPopular: true,
    isFavorite: true,
  },
  {
    id: 'services',
    name: 'Services',
    description: 'Professional services.',
    icon: 'account-tie',
    color: '#1F7856',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=640&h=480&fit=crop',
    price: '$150',
    location: 'Service Center',
    isPopular: false,
    isFavorite: false,
  },
];

export const PROMOTIONS = [
  {
    id: '1',
    title: '20% Off Handyman Service!',
    subtitle: 'Limited time offer on your first booking.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=640&h=480&fit=crop',
    buttonText: 'Learn More',
  },
  {
    id: '3',
    title: 'Fast Delivery Available',
    subtitle: 'Get your packages delivered same day.',
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=640&h=480&fit=crop',
    buttonText: 'Order Now',
  },
];

