export const mockListings = [
  // Electronics
  {
    id: '1',
    title: 'iPhone 15 Pro Max - 256GB - Brand New',
    price: 1299,
    category: 'Electronics',
    location: 'New York, NY',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=300&fit=crop',
    description: 'Brand new iPhone 15 Pro Max, unopened box. Latest model with all features.',
    featured: true,
    seller: {
      name: 'John Doe',
      rating: 4.8,
    },
  },
  {
    id: '2',
    title: 'MacBook Pro M3 - 14 inch - 512GB',
    price: 1999,
    category: 'Electronics',
    location: 'San Francisco, CA',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=300&fit=crop',
    description: 'Excellent condition MacBook Pro, barely used. Comes with original box and charger.',
    featured: false,
    seller: {
      name: 'Jane Smith',
      rating: 4.9,
    },
  },
  {
    id: '3',
    title: 'Samsung 65" 4K Smart TV',
    price: 899,
    category: 'Electronics',
    location: 'Los Angeles, CA',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop',
    description: 'Samsung 65 inch 4K UHD Smart TV. Perfect condition, wall mount included.',
    featured: true,
    seller: {
      name: 'Mike Johnson',
      rating: 4.7,
    },
  },
  // Real Estate
  {
    id: '4',
    title: 'Modern 2BR Apartment in Downtown',
    price: 2500,
    category: 'Real Estate',
    location: 'Seattle, WA',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
    description: 'Beautiful modern apartment with great views. Fully furnished, available immediately.',
    type: 'rent',
    featured: true,
    seller: {
      name: 'Real Estate Pro',
      rating: 4.8,
    },
  },
  {
    id: '5',
    title: 'Luxury 4BR House with Garden',
    price: 850000,
    category: 'Real Estate',
    location: 'Austin, TX',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400&h=300&fit=crop',
    description: 'Stunning 4 bedroom house with large garden and modern amenities.',
    type: 'sale',
    featured: true,
    seller: {
      name: 'Premium Homes',
      rating: 5.0,
    },
  },
  {
    id: '6',
    title: 'Cozy Studio Apartment',
    price: 1200,
    category: 'Real Estate',
    location: 'Portland, OR',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=300&fit=crop',
    description: 'Perfect studio apartment for students or young professionals.',
    type: 'rent',
    featured: false,
    seller: {
      name: 'City Rentals',
      rating: 4.6,
    },
  },
  // Jobs
  {
    id: '7',
    title: 'Senior Software Engineer - Remote',
    category: 'Jobs',
    location: 'Remote',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop',
    description: 'Looking for an experienced software engineer to join our growing team. Full-time remote position.',
    salary: '$120k - $150k',
    featured: true,
    seller: {
      name: 'Tech Corp',
      rating: 4.9,
    },
  },
  {
    id: '8',
    title: 'Marketing Manager - Full Time',
    category: 'Jobs',
    location: 'Chicago, IL',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    description: 'Experienced marketing manager needed for fast-growing startup.',
    salary: '$80k - $100k',
    featured: false,
    seller: {
      name: 'Startup Inc',
      rating: 4.5,
    },
  },
  {
    id: '9',
    title: 'Graphic Designer - Part Time',
    category: 'Jobs',
    location: 'Miami, FL',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
    description: 'Creative graphic designer needed for part-time position. Flexible hours.',
    salary: '$30 - $40/hour',
    featured: false,
    seller: {
      name: 'Creative Agency',
      rating: 4.7,
    },
  },
  // Services
  {
    id: '10',
    title: 'Professional House Cleaning Service',
    category: 'Services',
    location: 'Boston, MA',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop',
    description: 'Experienced cleaning service for homes and offices. Fully insured and bonded.',
    price: 150,
    featured: true,
    seller: {
      name: 'Clean Pro',
      rating: 4.8,
    },
  },
  {
    id: '11',
    title: 'Plumbing & Electrical Repairs',
    category: 'Services',
    location: 'Denver, CO',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=300&fit=crop',
    description: 'Licensed plumber and electrician available for all repair needs.',
    price: 100,
    featured: false,
    seller: {
      name: 'Fix It Now',
      rating: 4.9,
    },
  },
  {
    id: '12',
    title: 'Personal Trainer - Home Sessions',
    category: 'Services',
    location: 'Phoenix, AZ',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
    description: 'Certified personal trainer offering home workout sessions.',
    price: 75,
    featured: false,
    seller: {
      name: 'Fit Life',
      rating: 4.6,
    },
  },
];

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: 'laptop', color: '#3B82F6' },
  { id: 'real-estate', name: 'Real Estate', icon: 'home', color: '#10B981' },
  { id: 'jobs', name: 'Jobs', icon: 'briefcase', color: '#F59E0B' },
  { id: 'services', name: 'Services', icon: 'wrench', color: '#8B5CF6' },
];

